# Generated by Django 6.0.5 on 2026-05-27 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('terisi', 'Terisi')], default='tersedia', max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='kamar/')),
                ('lantai', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('umur', models.IntegerField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('no_hp', models.CharField(max_length=15)),
                ('scan_ktp', models.ImageField(upload_to='ktp/')),
                ('durasi', models.IntegerField(choices=[(1, '1 Bulan - Rp 1.000.000'), (6, '6 Bulan - Rp 6.000.000'), (12, '12 Bulan - Rp 12.000.000')], default=1)),
                ('total_harga', models.BigIntegerField(default=0)),
                ('tanggal_mulai', models.DateField(blank=True, null=True)),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Review'), ('disetujui', 'Disetujui - Menunggu Pembayaran'), ('menunggu_verifikasi', 'Menunggu Verifikasi Bayar'), ('aktif', 'Aktif'), ('ditolak', 'Ditolak'), ('selesai', 'Selesai / Tidak Diperpanjang')], default='menunggu', max_length=25)),
                ('tanggal_ajuan', models.DateTimeField(auto_now_add=True)),
                ('catatan_admin', models.TextField(blank=True)),
                ('kamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kost.kamar')),
            ],
        ),
        migrations.CreateModel(
            name='BuktiBayar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_bukti', models.ImageField(upload_to='bukti_bayar/')),
                ('catatan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Verifikasi'), ('verified', 'Verified'), ('ditolak', 'Ditolak')], default='menunggu', max_length=10)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kost.pengajuan')),
            ],
        ),
    ]
